services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./api-logs:/logs

  feedback:
    build: ./feedback
    ports:
      - "8080:8080"
    volumes:
      - ./feedback/dist:/app/dist:ro
      - ./feedback_files:/app/feedback_files
