name: Xtu EMS SDK test

on:
  push:
    branches:
      - master
      - develop
      - release
    tags:
      - auto_test
      - release
      - pre_release

env:
  XTU_USERNAME: ${{ secrets.XTU_USERNAME }}
  XTU_PASSWORD: ${{ secrets.XTU_PASSWORD }}

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10", "3.11", "3.12" ]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest wheel setuptools
      - name: Build wheel
        run: sh build.sh

      - name: Install XTU_EMS SDK
        run: pip install --no-index --find-links=./dist xtu-ems

      - name: Add source code folder to PYTHONPATH
        env:
          PYTHONPATH: "${{ github.workspace }}/src"  # 添加项目文件夹到 PYTHONPATH
        run: echo "PYTHONPATH is set to $PYTHONPATH"
      - name: PyTest with SDK
        run: |
          cd tests
          pytest
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.python-version }}
          path: |
            dist
