name: Xtu EMS SDK test

on: [ push, fork, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10", "3.11", "3.12" ]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest wheel setuptools
      - name: PyTest with SDK
        env:
          XTU_USERNAME: ${{ secrets.XTU_USERNAME }}
          XTU_PASSWORD: ${{ secrets.XTU_PASSWORD }}
          PYTHONPATH: "${{ github.workspace }}/src"
        working-directory: ./tests
        run: |
          pip install pytest pytest-html pytest-xdist
          pytest -n auto --html=test-reports/report-${{ matrix.python-version }}.html --self-contained-html

      - name: Upload pytest test results
        uses: actions/upload-artifact@v4
        with:
          compression-level: 0
          name: pytest-results-${{ matrix.python-version }}
          path: tests/test-reports/report-${{ matrix.python-version }}.html
          # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}

      - name: Build wheel
        run: sh build.sh

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          compression-level: 9
          name: dist-${{ matrix.python-version }}
          path: |
            dist/xtu_ems-**.whl
